#!/bin/bash
#
# Generate systemd service and path units for witnessd, and add them
# to user's local systemd configuration

set -Eeuo pipefail

service_unit=$(systemd-escape --path --template witnessd@.service "$1")
path_unit=$(systemd-escape --path --template witnessd@.path "$1")
exec_path="$2"
user_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/"
dropins_dir="${user_config_dir}${service_unit}.d"
dropin_conf="${user_config_dir}${service_unit}.d/${exec_path##*/}.conf"

echo
echo "witnessd-add: generate systemd service and path units, and add them to user's local systemd config"
echo
echo "WARNING! This script has no safety/sanity checks. Use at your own risk!"
echo
echo "Path to be watched: $1"
echo "Executable to invoke (path in systemd format, e.g. %h/.local/bin/myscript.sh): $2"
shift 2
echo "Additional arguments for the executable: $*"
echo "Systemd service unit file: ${service_unit}"
echo "Systemd path unit file: ${path_unit}"
echo "Systemd local user config directory: ${user_config_dir}"
echo "Systemd service drop-ins directory: ${dropins_dir}"
echo "Systemd service drop-in config file: ${dropin_conf}"
echo

read -r -n 1 -p "Proceed? [y/N] "
if [[ $REPLY =~ ^[Yy]$ ]]; then

	set -o noclobber
	echo
	echo -n "Copying template units to systemd local user config dir... "

	cp witnessd@.service "${user_config_dir}"
	cp witnessd@.path "${user_config_dir}"

	echo "Done!"
	echo -n "Creating drop-in directory and config file... "

	mkdir "${dropins_dir}"

	cat <<EOF >"${dropin_conf}"
# ${dropin_conf}
# This file was generated by witnessd-add on $(date)
[Unit]
Description="Run an executable when local path gets modified"
Documentation=https://github.com/roadkell/witnessd
[Service]
Environment=WITNESSD_EXEC="${exec_path}"
Environment=WITNESSD_ARGS="$@"
EOF

	echo "Done!"
	echo -n "Enabling systemd service and path units... "

	systemctl --user enable "${service_unit}"
	systemctl --user enable --now "${path_unit}"

	echo "Done!"

fi
